from typing import Protocol, Any


class DynamoTable(Protocol):
    def query(self, **kwargs) -> dict[str, Any]: ...
    def get_item(self, *, Key: dict) -> dict: ...
    def put_item(self, Item: dict[str, Any], **kwargs) -> Any: ...
    def update_item(self, **kwargs) -> Any: ...
    def delete_item(self, **kwargs) -> Any: ...