from typing import Protocol, Any


class DynamoTable(Protocol):
    def query(self, **kwargs) -> dict[str, Any]: ...
    def put_item(self, item: dict[str, Any], **kwargs) -> Any: ...
    def update_item(self, **kwargs) -> Any: ...
    def delete_item(self, **kwargs) -> Any: ...